default_install_hook_types:
  - pre-commit
  - post-checkout
  - post-merge
  - post-rewrite
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.4
    hooks:
      - id: ruff-check
        args: [ --fix ]
      - id: ruff-format
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: 'requirements.txt'
      - id: end-of-file-fixer
      - id: check-yaml
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.8.0
    hooks:
      - id: uv-lock
      - id: uv-export
        args: ['-o','requirements.txt','-q']

# sets up .pre-commit-ci.yaml to ensure pre-commit dependencies stay up to date
ci:
  autoupdate_schedule: weekly
  skip: []
  submodules: false
