# -*- coding: utf-8 -*-
"""markovify-derby-names.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iJ6Ib0NcRGv-ihxkmPt8ggHwfqnjrzGK
"""

from pathlib import Path
import markovify
import requests

MIN_STATE_SIZE = 2
MAX_STATE_SIZE = 5
NAMES_URL = "https://raw.githubusercontent.com/bdunnette/derby-name-scraper/main/derby_names_ascii.txt"
MODEL_PATH = Path("model")

names = requests.get(url=NAMES_URL).text

name_set = set(names.split(sep="\n"))


class SentencesByChar(markovify.Text):
    def word_split(self, sentence):
        return list(sentence)

    def word_join(self, words):
        return "".join(words)


for state_size in range(MIN_STATE_SIZE, MAX_STATE_SIZE + 1):
    print(f"State Size: {state_size}")

    word_model = markovify.NewlineText(
        input_text=names, state_size=state_size, well_formed=False
    )
    word_model.compile(inplace=True)
    word_model_file = MODEL_PATH / f"word_{state_size}.json"
    word_model_file.write_text(data=word_model.to_json())
    for i in range(5):
        print(word_model.make_sentence())

    char_model = SentencesByChar(input_text=names, state_size=state_size)
    char_model.compile(inplace=True)
    char_model_file = MODEL_PATH / f"char_{state_size}.json"
    char_model_file.write_text(data=char_model.to_json())
    for i in range(5):
        print(char_model.make_sentence())
